---
title: "聚类分析"
output: html_document
---

Detailed data attached at the end

## A hclustering example

```{r echo=FALSE}
Province.data0=read.csv("2015city.csv")
Province.data=as.matrix(Province.data0[,2:9])
rownames(Province.data)=Province.data0[,1]
region=Province.data0[,10]
```

### 1.缩放数据

```{r}
Province.data.sd=scale(Province.data)
```

### 2.计算距离

```{r}
Province=dist(Province.data.sd, method = "euclidean", diag=TRUE)
 #method:"euclidean"   euclide距离
 #       "maximum"     Chebyshev距离
 #       "manhattan"   绝对值距离
 #       "canberra"    Lance距离
 #       "binary"      定性变量的距离
 #       "minkowski"   minkowski距离, p是阶数
```

### 3.选择聚类算法

```{r}
hc1=hclust(Province, "single")  #最短距离法
hc2=hclust(Province, "complete")  #最长距离法
hc3=hclust(Province, "median")  #中间距离法
hc4=hclust(Province, "average")  #类平均法
hc5=hclust(Province, "centroid")  #重心法
hc6=hclust(Province, "mcquitty")  #相似分析法
hc7=hclust(Province, "ward.D")  #离差平方和
hc8=hclust(Province, "ward.D2")
```

### 4.结果可视化

```{r echo=FALSE}
opar=par(mar=c(5,4,4,2))
plot(hc1,hang=-1,cex=1, main="最短距离法")
re1=rect.hclust(hc1,k=5,border="red")
par(opar)
```

```{r echo=FALSE}
myplclust <- function(hclust, lab=hclust$labels, 
                      lab.col=rep(1,length(hclust$labels)), hang=0.1,...){
  ## modifiction of plclust for plotting hclust objects in colour
  ## Copyright Eva KF Chan 2009
  ## Arguments:
  ##    hclust:    hclust object
  ##    lab:        a character vector of labels of the leaves of the tree
  ##    lab.col:    colour for the labels; NA=default device foreground colour
  ##    hang:     as in hclust & plclust
  ## Side effect:
  ##    A display of hierarchical cluster with coloured leaf labels.
  y <- rep(hclust$height,2)
  x <- as.numeric(hclust$merge)
  y <- y[which(x<0)]
  x <- x[which(x<0)]
  x <- abs(x)
  y <- y[order(x)]
  x <- x[order(x)]
  plot(hclust, labels=FALSE, hang=hang, ... )
  text(x=x, y=y[hclust$order]-(max(hclust$height)*hang), 
       labels=lab[hclust$order], col=lab.col[hclust$order], 
       srt=90, adj=c(1,0.5), xpd=NA, ... )}
```

根据地区标注不同的color

```{r}
myplclust(hc7, lab.col = unclass(region))
legend("topright", pch=17, col=unique(unclass(region)), 
       legend=unique(region))
```

## K-Means Clustering: an example

```{r echo=FALSE}
library("cluster")
Arrest.data0=USArrests
Arrest.data=as.matrix(Arrest.data0[,-3])
rownames(Arrest.data)=1:50
Arrest.data.sd=scale(Arrest.data)
```

```{r}
km=kmeans(Arrest.data.sd, 3, nstart=100)
print(km)
sort(km$cluster)
clusplot(Arrest.data.sd, km$cluster, labels = 2)
```

## Appendix: datasets

```{r echo=FALSE}
library(knitr)
kable(Province.data0, caption="Province.data")
kable(USArrests, caption="USArrests")
```